### ISSUE TITLE
feat(mds-text): add CSS custom properties for text selection colors - [merged]

### ISSUE THREAD

**Issue by nicolatamburini** [magma-design-system/magma#347]
***In GitLab by @vittorio.vittori on Apr 20, 2022, 15:27 GMT+2:***

_Merges style/mds-text-selection -> dev_

## Description

È stato aggiunto dello stile per supportare le seguenti custom properties:

```css
/*
* @prop --selection-background: Sets the background-color of the text when the text is selected
* @prop --selection-color: Sets the color of the text when the text is selected
*/

:host {

  --selection-background: theme('colors.brand-maggioli-08');
  --selection-color: theme('colors.brand-maggioli-03');
}

:host::selection {
  background-color: var(--selection-background);
  color: var(--selection-color);
}
```

Per poter utilizzare questa feature, basta fare un override delle custom properties:

```html
<style>
  mds-text {
    --selection-background: red;
    --selection-color: blue;
  }
</style>
<mds-text>Select this text</mds-text>
```

## Related Issue

https://gitlab.com/maggiolispa/ricerca-sviluppo-new-media/design-system/-/issues/44

## Motivation and Context

Questa feature aggiunge al possibilità di colorare il colore del testo quando serve, come nel caso di `mds-note` che ha una lista di variant legate ai colori label come descritto in [questa merge request][mr-6].

## How Has This Been Tested?

La feature è stata testata nella [merge request #6][mr-6].

## Screenshots (if appropriate):

Alcuni esmepi di come può essere applicata la feature delle custom properties:

undefined

undefined

[mr-6]: https://gitlab.com/maggiolispa/ricerca-sviluppo-new-media/design-system/-/merge_requests/6

**Assignees:** vittorio.vittori

**Reviewers:** andrea.pruccoli

**Approved by:** andrea.pruccoli

*Migrated from GitLab: https://gitlab.com/maggiolispa/ricerca-sviluppo-new-media/magma/design-system/-/merge_requests/7*
