### ISSUE TITLE
mds-text / Add custom properties selection-background and selection-color

### ISSUE THREAD

**Issue by nicolatamburini** [magma-design-system/magma#44]
***In GitLab by @vittorio.vittori on Apr 19, 2022, 17:35 GMT+2:***

## Proposal impact

Impacts the following Design System projects:

- Stencil (web components)

## Is your proposal related to a problem?

Al momento `mds-text` non consente di personalizzare lo pseudo selettore `::selection`, di conseguenza supporta solo un colore predefinito impostato eventualmente in body. Questo è un limite tecnico facilmente aggirabile con le custom properties.

## Describe the solution you'd like

È possibile risolvere il problema implementando delle API basate sulle custom properties, come ad esempio `--selection-background` e `--selection-color`.

## Describe alternatives you've considered

Generalmente questa è considerata una best practice per i web component quando si parla di personalizzazione degli stili.

## Possible Implementation

Può essere sufficiente aggiungere delle custom properties come queste:

```css
:host {
  /* utilizzando tailwindcss */
  --selection-background: theme('colors.brand-maggioli-08');
  --selection-color: theme('colors.brand-maggioli-03');
}

:host::selection {
  background-color: var(--selection-background);
  color: var(--selection-color);
}
```

*Migrated from GitLab: https://gitlab.com/maggiolispa/ricerca-sviluppo-new-media/magma/design-system/-/work_items/44*
